# Convenience file for adding additional packages to renv lockfile that are
# wrongly marked as not used
library(backports)
library(boot)
library(Deriv)
library(doBy)
library(httpuv)
library(later)
library(lme4)
library(microbenchmark)
library(minqa)
library(nloptr)
library(pbkrtest)
library(promises)
library(RcppEigen)
library(rootSolve)
library(shiny)
library(snow)
library(sourcetools)
library(survC1)
library(xtable)